AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2022-10-31
Description: Code Deploy sam template
Globals:
    Function:
        Timeout: 20
        MemorySize: 512
Resources:
  CDLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.amazonaws.handler.GetOrderHandler::handleRequest
      Runtime: python3.6
      Role: 'arn:aws:iam::577107568078:role/LambdaRole0256'
      Events:
        GetApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api
            Method: get
      
      Environment:
        Variables:
          REGION: us-west-1
